apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: email-service
build:
  tagPolicy:
    # Use latest for development
    sha256: {}
  artifacts:
    - image: notebook/email-service
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"

profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit: {}
  - name: staging
    build:
      tagPolicy:
        gitCommit: {}